version: "3"
services:
    web:
        image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
        volumes: 
            - .:/app
        ports:
            - "5000:5000"
            - "5001:5001"
        depends_on:
            - db
        working_dir: /app
        command: "dotnet run"
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        ports: 
            - 1444:1433
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"